import type { Media } from './types';

export const songs: Media[] = [
	{
		id: '1ghy5k',
		imageSrc: '/src/assets/images/the-las.jpg',
		imageAlt: "Albumomslag för The La's",
		creator: "The La's",
		title: 'There She Goes',
		length: 162,
	},
	{
		id: '5sd6rt',
		imageSrc: '/src/assets/images/oasis.jpg',
		imageAlt: 'Albumomslag för Oasis – Definitely Maybe',
		creator: 'Oasis',
		title: 'Live Forever',
		length: 276,
	},
	{
		id: 'er8ko5',
		imageSrc: '/src/assets/images/the-stone-roses.jpg',
		imageAlt: 'Albumomslag för The Stone Roses',
		creator: 'The Stone Roses',
		title: 'I Wanna Be Adored',
		length: 292,
	},
	{
		id: 'd8pl6n',
		imageSrc: '/src/assets/images/arctic-monkeys.jpg',
		imageAlt:
			"Albumomslag för Arctic Monkeys – Whatever People Say I Am, That's What I'm Not",
		creator: 'Arctic Monkeys',
		title: 'I Bet You Look Good on the Dancefloor',
		length: 173,
	},
	{
		id: 'rt5gnj',
		imageSrc: '/src/assets/images/blur.jpg',
		imageAlt: 'Albumomslag för Blur – Parklife',
		creator: 'Blur',
		title: 'Girls & Boys',
		length: 258,
	},
	{
		id: 'eu56cf',
		imageSrc: '/src/assets/images/the-verve.png',
		imageAlt: 'Albumomslag för The Verve – Urban Hymns',
		creator: 'The Verve',
		title: 'Bitter Sweet Symphony',
		length: 358,
	},
	{
		id: '54dty3',
		imageSrc: '/src/assets/images/oasis2.jpeg',
		imageAlt: "Albumomslag för Oasis – (What's the Story) Morning Glory?",
		creator: 'Oasis',
		title: 'Wonderwall',
		length: 258,
	},
	{
		id: 'eslo56',
		imageSrc: '/src/assets/images/radiohead.png',
		imageAlt: 'Albumomslag för Radiohead – OK Computer',
		creator: 'Radiohead',
		title: 'No Surprises',
		length: 229,
	},
	{
		id: '1vbh2g',
		imageSrc: '/src/assets/images/coldplay.png',
		imageAlt: 'Albumomslag för Coldplay – Parachutes',
		creator: 'Coldplay',
		title: 'Yellow',
		length: 269,
	},
	{
		id: '5gjch5',
		imageSrc: '/src/assets/images/suede.jpg',
		imageAlt: 'Albumomslag för Suede – Suede',
		creator: 'Suede',
		title: 'Animal Nitrate',
		length: 206,
	},
];
